services:
  db:
    image: mysql:8.1.0
    hostname: mysql_db
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: quark
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - quark_net

  adminer:
    image: adminer:4.8.1
    hostname: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - quark_net

volumes:
  mysql-db:

networks:
  quark_net:
    name: quark_net
